// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProtocolSystemDBM.Migrations
{
    [DbContext(typeof(ProtocolSystemDbContext))]
    [Migration("20250216201406_InitializeDataBaseWithAllTables")]
    partial class InitializeDataBaseWithAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProtocolSystemDBM.Models.Protocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("closing_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("opening_date");

                    b.Property<Guid>("ProtocolStatusId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("protocol_status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("protocols", (string)null);
                });

            modelBuilder.Entity("ProtocolSystemDBM.Models.ProtocolFollow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("action_date");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action_description");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("protocol_id");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("protocol_follows", (string)null);
                });

            modelBuilder.Entity("ProtocolSystemDBM.Models.ProtocolStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("protocol_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2b32f72-2c91-47f6-b0a9-63e9b44b33f9"),
                            Deleted = false,
                            Name = "Criado"
                        },
                        new
                        {
                            Id = new Guid("f34be16e-d2ae-45d7-8f97-060f0cd541b2"),
                            Deleted = false,
                            Name = "Em processamento"
                        },
                        new
                        {
                            Id = new Guid("be0f2111-f6da-4208-b6f7-6e63f27b0428"),
                            Deleted = false,
                            Name = "Atendido"
                        });
                });

            modelBuilder.Entity("ProtocolSystemDBM.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProtocolSystemDBM.Models.Protocol", b =>
                {
                    b.HasOne("ProtocolSystemDBM.Models.ProtocolStatus", "ProtocolStatus")
                        .WithMany("Protocols")
                        .HasForeignKey("ProtocolStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProtocolSystemDBM.Models.User", "User")
                        .WithMany("Protocols")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProtocolStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProtocolSystemDBM.Models.ProtocolFollow", b =>
                {
                    b.HasOne("ProtocolSystemDBM.Models.Protocol", "Protocol")
                        .WithMany("ProtocolFollows")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("ProtocolSystemDBM.Models.Protocol", b =>
                {
                    b.Navigation("ProtocolFollows");
                });

            modelBuilder.Entity("ProtocolSystemDBM.Models.ProtocolStatus", b =>
                {
                    b.Navigation("Protocols");
                });

            modelBuilder.Entity("ProtocolSystemDBM.Models.User", b =>
                {
                    b.Navigation("Protocols");
                });
#pragma warning restore 612, 618
        }
    }
}
